// Command genvectors writes the test vectors used by p/drand.
//
// It fetches real evmnet beacons from drand, checks each one with the kyber
// reference (internal/evmnet), computes hash-to-G1 outputs with kyber, and
// writes them as a gno test file so the on-chain port is tested against the
// reference without network access.
//
//	go run ./cmd/genvectors -out p/drand/vectors_test.gno
package main

import (
	"bytes"
	"encoding/hex"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"log"
	"net/http"
	"os"
	"time"

	"github.com/albttx/gno-drand/internal/evmnet"
)

type beacon struct {
	Round      uint64 `json:"round"`
	Signature  string `json:"signature"`
	Randomness string `json:"randomness"`
}

// Fixed rounds, so regenerating gives the same file.
var rounds = []uint64{1, 2, 1000, 1000000, 10000000, 20000000, 21167346}

func main() {
	out := flag.String("out", "p/drand/vectors_test.gno", "output gno file")
	api := flag.String("api", "https://api.drand.sh", "drand HTTP endpoint")
	flag.Parse()

	client := &http.Client{Timeout: 10 * time.Second}
	var beacons []beacon
	for _, r := range rounds {
		b, err := fetch(client, *api, r)
		if err != nil {
			log.Fatalf("round %d: %v", r, err)
		}
		sig, _ := hex.DecodeString(b.Signature)
		if err := evmnet.Verify(b.Round, sig); err != nil {
			log.Fatalf("round %d does not verify: %v", r, err)
		}
		if rnd := evmnet.Randomness(sig); hex.EncodeToString(rnd[:]) != b.Randomness {
			log.Fatalf("round %d: randomness mismatch", r)
		}
		beacons = append(beacons, b)
	}

	var buf bytes.Buffer
	fmt.Fprintln(&buf, "// Code generated by cmd/genvectors. DO NOT EDIT.")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "package drand")
	fmt.Fprintln(&buf)
	fmt.Fprintln(&buf, "type beaconVector struct {\n\tround uint64\n\tsig string\n\trandomness string\n}")
	fmt.Fprintln(&buf, "type hashVector struct {\n\tmsg string\n\tpoint string\n}")
	fmt.Fprintln(&buf, "// Real evmnet beacons, verified with drand/kyber.")
	fmt.Fprintln(&buf, "var beaconVectors = []beaconVector{")
	for _, b := range beacons {
		fmt.Fprintf(&buf, "\t{%d, %q, %q},\n", b.Round, b.Signature, b.Randomness)
	}
	fmt.Fprintln(&buf, "}")
	fmt.Fprintln(&buf, "// Hash-to-G1 outputs computed by drand/kyber with the evmnet DST.")
	fmt.Fprintln(&buf, "var hashVectors = []hashVector{")
	for _, m := range hashMessages() {
		fmt.Fprintf(&buf, "\t{%q, %q},\n", hex.EncodeToString(m), hex.EncodeToString(evmnet.HashToG1(m)))
	}
	fmt.Fprintln(&buf, "}")

	src, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(*out, src, 0o644); err != nil {
		log.Fatal(err)
	}
	log.Printf("wrote %d beacons and %d hash vectors to %s", len(beacons), len(hashMessages()), *out)
}

func hashMessages() [][]byte {
	msgs := [][]byte{{}, []byte("abc")}
	for _, r := range []uint64{1, 2, 3, 42, 21167346} {
		msgs = append(msgs, evmnet.Message(r))
	}
	return msgs
}

func fetch(c *http.Client, api string, round uint64) (beacon, error) {
	var b beacon
	resp, err := c.Get(fmt.Sprintf("%s/%s/public/%d", api, evmnet.ChainHash, round))
	if err != nil {
		return b, err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return b, fmt.Errorf("http %s", resp.Status)
	}
	err = json.NewDecoder(resp.Body).Decode(&b)
	return b, err
}
